### ISSUE TITLE
arrange by star count or put star count next to each library

### ISSUE THREAD

**Issue by mrigdon** [vsouza/awesome-ios#1093] opened 2016-09-01 20:22 UTC
I'm one of those people who has to make sure I'm using the best/most supported library for everything. I'm trying to find the Activity Indicator library with the highest stars/most functionality, and it sucks to click through each one. It would be beneficial to do what I have said in the title of this issue.

**Comment by dkhamsing** [comment] 2016-09-01 20:29
dupe of #756, @lfarah did we decide to have this functionality one http://awesomeios.com/ ?

**Comment by lfarah** [comment] 2016-09-01 21:00
that's on @vsouza

**Comment by lfarah** [comment] 2016-09-06 22:16
Let's close this one and comment on #756

**Comment by lfarah** [comment] 2016-09-07 07:41
I think we can reopen this since this is way simpler than the datatables.
I created [this json](https://gist.github.com/lfarah/69bf800869a4633c7d5d514c8e0f301e) that filters and sorts libraries per category per CocoaPods quality index.

@dkhamsing what can we do from here?

**Comment by lfarah** [comment] 2016-09-07 07:44
@mrigdon and for you, please go ahead and look through the best activity indicator libraries in the json file! 😄

**Comment by dkhamsing** [comment] 2016-09-07 11:51
@lfarah you want to do a one time conversion of json to readme?

**Comment by lfarah** [comment] 2016-09-07 16:26
@vsouza what do you think?

**Comment by mrigdon** [comment] 2016-09-07 22:40
thanks @lfarah for the json

**Comment by lfarah** [comment] 2016-09-07 22:41
@mrigdon you're welcome. Let us know what library you chose! 😉

**Comment by victorgama** [comment] 2016-09-08 00:34
@lfarah @dkhamsing For a while now I wanted to make an API to track stargazers and search the list. Although the markdown-parsing phase is quite much functional (had to rewrite it in the last hour, but seems quite stable and fast now), caching GH's response is a TODO, and I would also need @vsouza to configure a webhook to reindex when any PR is merged.
As I would host it on my own server, awesomeios.com could display results through AJAX requests, and even search remote data. 

What you guys think? It's quite much trivial to build it up. And will work alright after the first index, since we will surely hit GH's rate limit (perhaps not, since authenticated requests have a 5k limit and we have less than 3k entries on the list).

**Comment by dkhamsing** [comment] 2016-09-08 02:33
Do we still update the README?

**Comment by victorgama** [comment] 2016-09-08 02:40
@dkhamsing I think that initially, stargazers count (together with search/sorting mechanisms) would be available only on awesomeios.com, but we can also find a way to automatically update the README file with this information.

IMHO, if we eventually show this field on each entry, we should also consider formatting the whole list in tables, or else it would get really clobbered.

**Comment by vsouza** [comment] 2016-09-08 16:41
Sort by stars is not relevant, it does not measure the quality of a lib for stars, (the amount of NPM packages that do nothing useful and has many stars prove it).

The organization must be made alphabetically or by order of arrival. Is the roadmap awesomeios.com have different filters and sort order.

I believe the awesome-ios fulfills the aim of this organization we have, more features can be placed in awesomeios.com.

IMHO the list is well organized and put it in tables or insert more indicators such as stars, would only make it more polluted.

**Comment by dkhamsing** [comment] 2016-09-08 16:54
my vote is still chronological for the readme = no change

**Comment by victorgama** [comment] 2016-09-08 16:57
@vsouza 

> IMHO the list is well organized and put it in tables or insert more indicators such as stars, would only make it more polluted.

I do agree with you, hence as mentioned [here](https://github.com/vsouza/awesome-ios/issues/1093#issuecomment-245478100), and I quote:

> (...) stargazers count (together with search/sorting mechanisms) would be available **only** on awesomeios.com, but we can _also_ find a way to automatically update the README file with this information.

Let me know if you guys do plan to parse the readme and such, I can happily build this up for us together with the mentioned mechanisms. ✨

**Comment by dkhamsing** [comment] 2016-09-08 17:29
the features of sorting/filtering/searching are great, i hope they make it on to awesomeios.com

**Comment by victorgama** [comment] 2016-09-09 06:44
Well, will work on them next weekend. Will let you guys know when it's ready. ✨

**Comment by lfarah** [comment] 2016-09-09 08:26
@vsouza, we're not filtering from stars. We're filtering from quality index from CocoaPods.

You all wanna do a skype call so we can talk about it?

**Comment by lfarah** [comment] 2016-09-09 08:28
I agree with @vsouza and I don't think we should put a star count for every single library. That would pollute the '''README'''

**Comment by victorgama** [comment] 2016-09-09 08:36
@lfarah @vsouza Instead of a Skype call, why don't we keep the conversation just here? This way everyone stays updated on what's going on. 🙌

**Comment by dkhamsing** [comment] 2016-09-09 14:55
@lfarah so u put projects with high quality index at the top? how about those that do not support cocoapods

**Comment by lfarah** [comment] 2016-09-11 04:45
@dkhamsing that's a good question. For now, they would be after the CocoaPods projects, but later we could implement our own quality index.
I think that being CocoPods compatible is a way to measure quality since it makes it really easy to install and test libraries

**Comment by mrigdon** [comment] 2016-09-11 05:30
Man this sparked some controversy - just think sorting is chill.

**Comment by lfarah** [comment] 2016-09-11 06:43
I just checked and **only 54 libraries** don't support CocoaPods, against 1041.
If we take into account that out of these 54 libraries, **19 of them** are in the Server category and since CocoaPods is not supported on Linux, none of the server libraries will change position.
So in the end, only **35 out of 1041** libraries don't support CocoaPods.

**Comment by dkhamsing** [comment] 2016-09-11 13:34
Cool
So basically quality index of 0 if not using CocoaPods

**Comment by lfarah** [comment] 2016-09-12 18:23
Yes, and later we could create our own quality index

**Comment by ReDetection** [comment] 2016-09-23 03:59
Hi guys, I just wonder if you're going to add a "has tests" flag and filter? Because right at this moment I'm choosing the In-app purchase helper, and I can't find any unit-tested one :(

**Comment by lfarah** [comment] 2016-09-23 05:27
Hey @ReDetection, I'm sure I and @vsouza can come with a filter only for tests. Soon we'll be using CocoaPods' Quality Index and tests definitely count on this index.

Talking about In-app purchase libraries specifically, I'm sure it must be hard to write tests for that since it will always include certificates, payment, etc, so I don't know how these libraries could have tests.

**Comment by vsouza** [comment] 2017-01-12 13:24
@lfarah we can close this issue?

**Comment by miguelarauj1o** [comment] 2017-03-16 23:49
@lfarah, I'm closing this one. Feel free to reopen if you want.

**Closed by miguelarauj1o** 2017-03-16 23:49 UTC
Labels: enhancement, question
