### ISSUE TITLE
www.ioscreator.com down

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#1688] opened 2017-05-22 19:21 UTC
let's remove or close this issue on Jun 1

https://www.ioscreator.com/

**Comment by victorgama** [comment] 2017-05-22 19:33
Any idea how long is it down? Was iterating through some redirects today and stumbled on errors caused by iOSCreator on Travis. 🤔

**Comment by dkhamsing** [comment] 2017-05-22 19:35
not sure.. new problem I think ?

**Comment by victorgama** [comment] 2017-05-22 19:40
Probably. Last commit on @ioscreator's repository was 14 days ago.
Let's wait and remove (or hopefully, just close this one).

🙌

**Comment by miguelarauj1o** [comment] 2017-05-26 16:23
I'm closing this issue because **iOScreator** is back.
Feel free to reopen if you want to.

**Closed by miguelarauj1o** 2017-05-26 16:23 UTC
